[package]
name = "hello_world"
version = "0.1.0"
edition = "2021"
authors = ["june0619 <jjw50901@gmail.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]